# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_demande_planifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='planifier',
            name='centre',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Centres'),
        ),
    ]
