# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-12 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=255)),
                ('blood_type', models.CharField(choices=[('1', 'A+'), ('2', 'A-'), ('3', 'B+'), ('4', 'B-'), ('5', 'O+'), ('6', 'O-'), ('7', 'O+'), ('8', 'AB+'), ('9', 'AB-')], help_text='Your Blood Type', max_length=3)),
                ('phone', models.CharField(max_length=255)),
                ('location', models.CharField(help_text='Your location/address', max_length=255)),
                ('date_posted', models.DateField(auto_now_add=True, verbose_name='Alert posted on')),
                ('message', models.TextField(help_text='A message', max_length=255)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
