# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-13 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('blood_alert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='alert',
            name='date_time_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.datetime_safe.datetime.utcnow, verbose_name='Alert posted on'),
            preserve_default=False,
        ),
    ]
