# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_alert', '0002_auto_20170813_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='blood_type',
            field=models.CharField(choices=[('1', 'A+'), ('2', 'A-'), ('3', 'B+'), ('4', 'B-'), ('5', 'O+'), ('6', 'O-'), ('7', 'AB+'), ('8', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='alert',
            name='location',
            field=models.CharField(default='Your location/address', max_length=255),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(default='Add details in your message', max_length=255),
        ),
    ]
